name: Email Step Workflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24f2002242@ds.study.iitm.ac.in
        run: echo "Hello, world!"
