name: CI with Cache

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache dependencies (example: Node.js dependencies)
      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-163155e
          restore-keys: |
            cache-163155e

      # Step to prime the cache and show hit/miss
      - name: prime-cache-163155e
        run: |
          if [ "${{ steps.cache-node-modules.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
